export const SHORT_BANK: Record<string, string[]> = {
  acik: [
    'Mac acik oyuna yakin gorunuyor; iki takim da skor uretebilir.',
    'Tempo yuksek, gol sayisi ortalamanin uzerine cikabilir.',
    'Iki hucum hattinin da oyuna etki etmesi bekleniyor.',
    'Acilan skor oyunu daha da hareketlendirebilir.',
    'Gollu ve ritmi dusmeyen bir senaryo one cikiyor.',
    'Iki savunma da baski altinda kalabilir.',
    'Gol beklentisi bu maci digerlerinden ayiriyor.',
    'Karsilikli tehdit ureten bir eslesme profili var.',
  ],
  kilitli: [
    'Savunma dengesi one cikiyor; kontrollu bir mac bekleniyor.',
    'Goller kolay gelmeyebilir.',
    'Daha sabirli ve dusuk tempolu bir oyun olasi.',
    'Ilk gol gelene kadar denge korunabilir.',
    'Az gollu senaryo verilerle daha uyumlu.',
    'Iki takim da hata yapmamaya oncelik verebilir.',
    'Skorun gec acilmasi sasirtici olmaz.',
    'Savunma disiplini bu macin ana basligi gibi duruyor.',
  ],
  favori: [
    'Veriler bir tarafi biraz daha onde gosteriyor.',
    'Form ve genel tablo avantajli tarafi destekliyor.',
    'Macin kontrolu tek tarafa daha yakin olabilir.',
    'Ustunluk sinyali net ama kopuk bir mac garanti degil.',
    'Avantajli taraf oyunu kendi ritmine cekebilir.',
    'Taraf sinyali var; yine de tek gollu denge bozulabilir.',
    'Uretim ve savunma dengesi bir ekibi one tasiyor.',
    'Bu eslesmede agirlik merkezi bir tarafa kaymis durumda.',
  ],
  surpriz: [
    'Net bir taraf cikarmak zor; surprize acik bir mac.',
    'Veriler tek yone akmiyor.',
    'Bu eslesmede kucuk anlar sonucu belirleyebilir.',
    'Form ve tablo birbirini tam desteklemiyor.',
    'Belirsizlik seviyesi yuksek.',
    'Mac ici gelismeler yorumdan daha belirleyici olabilir.',
    'Iki takim da oyunda kalabilecek profilde.',
    'Bu maci canli akis daha net anlatabilir.',
  ],
  savunma: [
    'Savunma guvenligi oyunun merkezinde olacak gibi duruyor.',
    'Pozisyon kalitesi sayidan daha onemli olabilir.',
    'Tek golun maci belirleme ihtimali yuksek.',
    'Duran top ve gecis anlari belirleyici olabilir.',
    'Iki takim da geride dengeli kalmaya calisacaktir.',
    'Macin ritmini savunma disiplinleri belirleyebilir.',
    'Kontrollu baski ve hata bekleyen bir yapi var.',
    'Bu tip maclarda sabir en buyuk avantaj olur.',
  ],
  dengeli: [
    'Taraflar birbirine yakin profilde gorunuyor.',
    'Macin baslangici kontrollu ve dengeli olabilir.',
    'Net ustunluk sinyali cikmiyor.',
    'Ilk gol psikolojik avantaji buyutebilir.',
    'Dengeyi bozan detaylar sonuc uzerinde etkili olacak.',
    'Bu eslesmede ritim degisimi kritik olabilir.',
    'Form ve tablo birlikte bakildiginda mesafe sinirli.',
    'Dengeli bir akista sabirli kalan taraf kazanabilir.',
  ],
  ev_kalesi: [
    'Ev sahibi ic sahada daha guclu bir profil veriyor.',
    'Ic saha etkisi bu macin yonunu degistirebilir.',
    'Deplasman tarafi disarida daha kirilgan gorunuyor.',
    'Tribun ve saha aliskanligi ev sahibine ekstra destek veriyor.',
    'Ev sahibi kendi ritmini kurarsa ustunluk buyuyebilir.',
    'Ic saha performansi sezon ortalamasinin uzerinde.',
    'Bu macta ev sahibi etkisi dikkate alinmali.',
    'Evde oynayan taraf daha rahat ve daha guvenli gorunuyor.',
  ],
  gol_savasi: [
    'Iki taraf da gol bulabilir, ama ayni zamanda gol verebilir.',
    'Macin ana hikayesi savunmadan cok skor akisi olabilir.',
    'Acilan oyun daha fazla gol ihtimalini artiriyor.',
    'Savunma kirilganligi bu maci gollu profile tasiyor.',
    'Bu eslesmede skorun bir kez degil birkac kez degismesi olasi.',
    'Gol odakli bir ritim beklemek daha mantikli.',
    'Hucum gucu ve savunma aciklari ayni anda goruluyor.',
    'Iki kale de uzun sure rahat kalmayabilir.',
  ],
  form_donusu: [
    'Son haftalardaki ivme sezon ortalamasindan daha guclu sinyal veriyor.',
    'Form degisimi bu macin yonunu etkileyebilir.',
    'Guncel ivme, eski tabloyu kismen gecersiz kilabilir.',
    'Son maclar bir takimi daha diri gosteriyor.',
    'Bu eslesmede sezon verisi kadar guncel form da onemli.',
    'Yukselen ritim macin psikolojisini etkileyebilir.',
    'Bir taraf son donemde daha canli gorunuyor.',
    'Guncel trend bu maca ek anlam katiyor.',
  ],
};

export const MEDIUM_BANK: Record<string, string[]> = {
  acik: [
    'Iki takimin da hucum uretimi ve tempo istegi bu maci gollu bir profile tasiyor. Savunma aciklari da bu okumayi destekliyor.',
    'Macin ritmi yuksek gorunuyor. Ilk gol gelirse oyun daha da acilabilir ve iki taraf da skora katki verebilir.',
    'Gol beklentisi ortalamanin uzerinde. Taraf seciminden cok oyunun acik kalmasi daha guclu sinyal veriyor.',
    'Hucum profilleri birbirini besliyor. Bu nedenle macin uzun bolumunde tempo dusmeyebilir.',
    'Iki ekip de skor uretmeye yakin gorunuyor. Bu tip eslesmelerde ikinci yari daha fazla alan acabilir.',
    'Veriler, macin dar skor yerine hareketli bir akisla oynanma ihtimalini guclendiriyor.',
    'Savunmalarin tam guven vermemesi, gol beklentisini daha anlamli hale getiriyor.',
    'Oyun yapilari birlikte okundugunda bu maci gol senaryosu uzerinden okumak daha tutarli duruyor.',
  ],
  kilitli: [
    'Dusuk gol ortalamalari ve kontrollu oyun profili, maci sabir isteyen bir zemine tasiyor. Ilk gol kritik olacak.',
    'Iki takim da savunma dengesini bozmadan oynamaya yatkin. Bu nedenle dar skor senaryolari daha dogal gorunuyor.',
    'Macin ritmi kolay yukselmeyebilir. Duran top, ikinci top ve bireysel hata oyunu acan temel unsurlar olabilir.',
    'Gol uretimi sinirli gorunuyor. Bu da maci acele etmeyen, hata bekleyen bir yapiya yaklastiriyor.',
    'Savunma bloklari birbirine yakin seviyede. Bu tip eslesmelerde oyun uzun sure kilitli kalabilir.',
    'Kontrollu baslangic ve dusuk riskli oyun plani en olasi senaryo gibi duruyor.',
    'Iki taraf da skor vermemeyi, erken risk almaktan daha oncelikli gorebilir.',
    'Bu profil, seyir olarak sakin ama taktik olarak dikkat isteyen bir maca isaret ediyor.',
  ],
  favori: [
    'Form, puan tablosu ve uretim dengesi birlikte bakildiginda bir taraf digerinden biraz daha onde duruyor. Bu ustunluk oyunun kontrolune yansiyabilir.',
    'Veriler bir ekibi avantajli gosteriyor. Yine de bu avantaj daha cok oyun kontrolu ve kaybetmeme tarafinda daha net okunuyor.',
    'Hucum ve savunma dengesi ayni tarafta toplanmis durumda. Bu, maci tek yone yaklastiran en guclu veri katmani.',
    'Ustunluk sinyali var, fakat macin tek tarafli akacagi kesin degil. Rakibin oyunda kalma sansi ilk bolumdeki dirence bagli.',
    'Avantajli taraf kendi ritmini kurarsa mac daha okunur hale gelir. Erken gol ise bu farki buyutebilir.',
    'Veriler agirligi bir tarafa veriyor. Riski daha dengeli okumak icin bu ustunlugu sonuc kadar oyun kontrolu olarak da dusunmek gerekir.',
    'Taraf sinyali netlesiyor; buna ragmen macin kopmasi icin sahadaki ilk kirilma ani onemli olacak.',
    'Bu eslesmede genel tablo, bir ekibin daha derli toplu ve daha guvenli geldigini soyluyor.',
  ],
  surpriz: [
    'Bu eslesmede net bir taraf yorumuna gitmek zor. Form, savunma ve tempo verileri ayni yone guclu bicimde bakmiyor.',
    'Belirsizlik seviyesi yuksek. Bu nedenle maci sadece pre-match verilerle degil, oyun ici akisla birlikte okumak daha saglikli olur.',
    'Iki takim da farkli alanlarda avantaj tasiyor. Bu durum, macin sonucunu kucuk anlara ve karar kalitesine birakiyor.',
    'Veriler birbirini tam desteklemiyor. Bu tip maclarda ilk gol, kirmizi kart ya da duran top gibi anlar yorumun onune gecebilir.',
    'Taraf secmekten cok riskin yuksek oldugunu not etmek daha dogru. Canli ritim burada daha degerli bilgi uretir.',
    'Form dalgali, tablo tam net degil. Bu da maci surprize acik ve yorumu zor bir profile tasiyor.',
    'Bu eslesmede tek bir senaryoya fazla guvenmek dogru olmaz. Oyun ici denge cok cabuk degisebilir.',
    'Mac oncesi tablo kesin bir sonuc soylemiyor; daha cok olasiliklarin birbirine yakin oldugu bir yapı sunuyor.',
  ],
  savunma: [
    'Savunma guvenligi bu eslesmenin ana ekseni gibi gorunuyor. Oyun uzun sure kontrollu ve parcali akabilir.',
    'Iki takim da geride alan vermemeye odaklanirsa, macin temposu belirgin sekilde dusuk kalabilir.',
    'Bu tip profillerde pozisyon sayisindan cok pozisyon kalitesi onem kazanir. Tek bir duran top bile dengeyi bozabilir.',
    'Mac, hucum gosterisinden cok savunma organizasyonu ve sabir uzerinden okunuyor.',
    'Skor uretimi sinirli, savunma dikkati ise yuksek. Bu da dar skor ihtimalini guclendiriyor.',
    'Iki taraf da hata yapmamak isteyecektir. Bu nedenle ilk gol gelene kadar oyun temkinli kalabilir.',
    'Savunma verileri, bu macin acik oyundan cok disiplinli yerlesimle ilerleyebilecegini gosteriyor.',
    'Macin ana sorusu kim daha cok pozisyon bulacak degil, kim tek kritik ani daha iyi yonetecek sorusu olabilir.',
  ],
  dengeli: [
    'Taraflarin genel profili birbirine yakin. Macin ritmini bozacak asıl unsur, ilk gol ya da ikinci yari ayarlari olabilir.',
    'Mac oncesi tablo belirgin bir taraf ustunlugu vermiyor. Bu da oyunu denge ve sabir eksenine tasiyor.',
    'Iki ekip de benzer guclu ve zayif alanlar tasiyor. Bu nedenle macin uzun bolumunde denge korunabilir.',
    'Veriler, kopmaktan cok olgunlasarak acilan bir maca isaret ediyor. Taktiksel detaylar fark yaratacak.',
    'Dengeli profilde ilk yarinin daha dikkatli gecmesi, ikinci yarida ise risk seviyesinin artis gostermesi olasi.',
    'Bu maci tek bir sayiya bakarak okumak zor. Form, savunma ve gol beklentisi birbirine yakin bir resim veriyor.',
    'Taraflar arasindaki mesafe sinirli. Bu nedenle oyun ici momentum, macin yorumundan daha hizli agirlik kazanabilir.',
    'Denge bozulursa genelde tek bir veri degil, birkac kucuk detay ust uste gelerek bozulacak gibi duruyor.',
  ],
  ev_kalesi: [
    'Ev sahibi kendi sahasinda daha guclu bir profil veriyor. Bu ustunluk sadece his degil, performans verileriyle de destekleniyor.',
    'Ic saha etkisi bu macta gercek bir avantaj uretiyor. Ev sahibi kendi ritmine daha kolay ulasabilir.',
    'Deplasman takiminin dis saha performansi daha kirilgan. Bu nedenle macin dogal akisi ev sahibi lehine kayabilir.',
    'Tribun, saha aliskanligi ve ic saha verimi bir araya geldiginde ev sahibi tarafin zemini daha saglam gorunuyor.',
    'Ev sahibi evinde daha rahat uretim yaparken deplasman tarafi disarida daha fazla savunma baskisi yasayabiliyor.',
    'Bu eslesmede ev sahibi etkisi psikolojik degil, sayisal olarak da hissediliyor.',
    'Ic saha performansi, sezon genel dengesine ekstra agirlik katiyor. Bu da macin yonunu etkileyecek temel faktorlürden biri.',
    'Ev sahibi oyun kontrolunu kurarsa bu maci kendi kosullarina daha kolay tasiyabilir.',
  ],
  gol_savasi: [
    'Iki takim da gol atma konusunda istekli, gol yeme konusunda ise tam guven vermiyor. Bu profil maci gollu senaryoya yaklastiriyor.',
    'Savunma kirilganligi iki tarafta da hissediliyor. Bu nedenle macin ana basligi skor akisi olabilir.',
    'Gol ortalamalari ve yenilen gol yapisi birlikte bakildiginda oyun acildikca daha hareketli hale gelebilir.',
    'Bu tip eslesmelerde ilk gol genelde frene degil, daha da hizlanan bir ritme neden olur.',
    'Iki taraf da top rakipteyken rahat hissettirmiyor. Bu da gol beklentisini dogal bicimde yukseltiyor.',
    'Macin hikayesi savunmadan cok hucum cevabi uzerinden yazilabilir. Karsilikli skor ihtimali yuksek.',
    'Hem tempo hem bitiricilik potansiyeli bu maci gol odakli bir profile tasiyor.',
    'Bu eslesmede "gol olur mu" sorusundan cok "oyun ne kadar acilir" sorusu daha anlamli duruyor.',
  ],
  form_donusu: [
    'Son haftalardaki ivme sezon geneline gore farkli bir hikaye anlatiyor. Bu nedenle guncel form burada ekstra agirlik kazaniyor.',
    'Bir tarafin son donem cikisi, kagit ustundeki sezon dengesini degistirebilir. Maci guncel ritimle birlikte okumak gerekiyor.',
    'Form grafiği degisen takimlar, sezon ortalamasindan daha farkli bir oyun seviyesi getirebilir. Bu mac da o profile yakin.',
    'Son maclardaki momentum farki, oyunun psikolojisini ve ozguven dengesini etkileyebilir.',
    'Bu eslesmede guncel form, genel tablo kadar onemli. Ivmeyi yakalayan taraf saha icinde daha cesur davranabilir.',
    'Bir takimin son donemdeki toparlanmasi ya da dususu, bu maci normalden daha degisken hale getiriyor.',
    'Form donusumu bu macin yorumunda temel katmanlardan biri. Sadece sezon toplamlarina bakmak eksik kalir.',
    'Son haftalarda guclenen taraf, bu maca rakibinden daha canli ve daha net planla cikabilir.',
  ],
};
