export const SHORT_BANK: Record<string, string[]> = {
  acik: [
    'Her iki kale de açık; tempolu ve gollü bir akış öne çıkıyor.',
    'Yüksek tempo öne çıkıyor.',
    'Açık oyun bu maçın doğal seyri gibi görünüyor.',
    'İki takımın oyun yapısı tempoyu yukarı çekebilir.',
    'Veriler gollü bir karşılaşmaya işaret ediyor.',
    'Hücum ağırlıklı bir eşleşme — karşılıklı gol kuvvetli ihtimal.',
    'Skor açılırsa durmayabilir; iki taraf da atakta güçlü.',
    'Yüksek ritim ve karşılıklı gol beklentisi bu maçı öne çıkarıyor.',
  ],
  kilitli: [
    'Savunmalar öne çıkıyor; az gollü ve kontrollü bir maç bekleniyor.',
    'Goller kolay gelmeyecek.',
    'Düşük tempolu, sabırlı bir karşılaşma öne çıkıyor.',
    'Kilitli bir eşleşme — gol bulmak zorlaşabilir.',
    'İki savunma bloğunun kıyaslaması; tempo düşük kalabilir.',
    'Az gollü senaryo istatistiksel olarak güçlü.',
    'Bekleyici oyun anlayışı bu maçın ritmini belirleyebilir.',
    'Savunma dengesi baskın; goller için mücadele uzayabilir.',
  ],
  favori: [
    'İstatistikler net avantaja işaret ediyor; tek yönlü bir senaryo olası.',
    'Belirgin istatistiksel üstünlük var.',
    'Form farkı belirgin; maç tek tarafa kayabilir.',
    'Veriler tek yönlü sonuçla uyumlu.',
    'Favorinin baskısını sürdürmesi durumunda maç kontrole girebilir.',
    'Rakip avantajı kırmak için erken fırsat aramak zorunda.',
    'İstatistiksel tablo net; güçlü taraf lehine senaryo baskın.',
    'Güçlü hücum ve sağlam savunma birleşimi belirgin fark yaratıyor.',
  ],
  surpriz: [
    'Sürpriz senaryoya açık — veriler net yön işaret etmiyor.',
    'Risk yüksek; herhangi bir sonuç mümkün.',
    'Değişken dinamikler maçı sürprizlere açık kılıyor.',
    'Net tercih güç; sahada her şey olabilir.',
    'Veriler belirsiz; anlık gelişmeler belirleyici olabilir.',
    'Bu tür maçlar çoğu zaman sürprizle biter.',
    'Her iki taraf da galip gelebilir; form çok dalgalı.',
    'Belirsizlik yüksek; senaryolar birbirini götürüyor.',
  ],
  savunma: [
    'Savunma blokları öne çıkıyor; goller için çalışılması gerekecek.',
    'Kontrollü ve dikkatli bir eşleşme bekleniyor.',
    'İlk golü bulan taraf yönetmede avantaj kazanabilir.',
    'Kale sıfır ihtimali göz ardı edilmemeli.',
    'Disiplinli savunma anlayışı düşük tempoya yol açabilir.',
    'Her iki takım da arkayı güvende tutmayı tercih ediyor.',
    'Savunma dengesinin belirleyeceği, sabırlı bir karşılaşma.',
    'Az gollü zemin bu maçın istatistiksel çerçevesi.',
  ],
  dengeli: [
    'Taraflar arasındaki fark sınırlı; kontrollü bir başlangıç daha olası.',
    'Net üstünlük sinyali çıkmıyor.',
    'İki ekip benzer bir profil çiziyor.',
    'Dengeli bir açılış daha olası; kopmak için tetikleyici gerekli.',
    'Güç dengesi yakın; küçük anlara bağlı kalabilir.',
    'Maç öncesi göstergeler belirgin fark yaratmıyor.',
    'Karşılaşma erken kopmaktan çok sabırlı bir ilerlemeye yakın.',
    'İki tarafın benzer profili kontrolün uzun süre ortada kalmasına yol açabilir.',
  ],
};

export const MEDIUM_BANK: Record<string, string[]> = {
  acik: [
    'Her iki takımın yüksek hücum üretimi bu maçı gol açısından zengin kılıyor. Savunma açıkları da bu tabloyu destekler nitelikte.',
    'Yüksek ritimli bir eşleşme bekleniyor. Tarafların birbirini çözmesiyle gol sayısı hızla artabilir.',
    'İki takımın oyun yapısı tempoyu yukarı çekebilir. Savunma pozisyonları geride kalınca skor hareketi kaçınılmaz olabilir.',
    'Hem ev sahibi hem deplasman yüksek gol geçmişiyle geliyor. 2.5 üst seçeneği istatistiksel destek buluyor.',
    'Hücum ortalamaları karşılıklı gol senaryosunu ön plana çıkarıyor. İkinci yarıda tempo korunabilir.',
    'Skor açıldığında durmayabilir; iki taraf da yüksek hücum kapasitesine sahip. Savunmaya geçmek zorunda kalan taraf zayıflayabilir.',
    'Taraflar birbirini zorlayan hücum profillerine sahip. Oyunun açık kalması bu maçın doğal senaryosu gibi görünüyor.',
    'Veriler hem tempo hem gol sayısını yukarı çekiyor. Defansif hataların bedeli bu tür eşleşmelerde çok daha ağır oluyor.',
  ],
  kilitli: [
    'Düşük gol ortalamaları bu maçı az gollü bir eşleşme çerçevesine oturtuyor. Savunma dengesinin öne çıkması bekleniyor.',
    'Her iki takımın kontrollü oynama alışkanlığı maçı dar ve kapışmalı bir zemine taşıyor. İlk gol çok kritik olacak.',
    'Savunma ağırlıklı profiller az gollü senaryoyu destekliyor. 0-1 ya da 1-0 gibi skorlar bu tablo için sürpriz sayılmaz.',
    'Gol üretiminde zorluğu olan takımların eşleşmesi; maç sabırlı bir akışla ilerleme eğiliminde. Sessiz bir mücadele de olası.',
    'İki savunma bloğunun kıyaslandığı bir karşılaşmaya benzeyebilir. Gollü senaryo için ek tetikleyici gerekli.',
    'Bekleyici profiller bu maçı sabırlı bir zemine taşıyor. Standart duran toplar belirleyici olabilir.',
    'Kontrollü ve yavaş açılan bir eşleşme bekleniyor. Her iki takım da gol vermemek adına temkinli oynayacaktır.',
    'Az gollü geçmişleri bu karşılaşmanın ritmini de belirleyebilir. İlk 45 dakika çoğu zaman kapalı geçiyor.',
  ],
  favori: [
    'Form ve istatistikler belirgin üstünlük gösteriyor. Rakip bu tabloyu tersine çevirmek için erken pozisyon aramak zorunda.',
    'Avantajlı taraf hücum ve savunmada önde; maçın kontrolü büyük ihtimalle lehine kalacak.',
    'İstatistiksel üstünlük net görünüyor. Favorinin baskısını sürdürmesi halinde rakip direnci giderek zorlaşabilir.',
    'Güçlü tarafın baskısını sürdürmesi durumunda galibiyet görece rahat gelebilir. Deplasman direnci belirleyecek.',
    'Veriler net avantaj tablosu çiziyor. Tek golle kilitlenme riski de göz önünde bulundurulmalı.',
    'Belirgin istatistiksel fark var; favorinin tempo düşürme tuzağına düşmemesi önemli.',
    'Güçlü taraf form, gol ortalaması ve savunmada önde. Maçın kontrolü büyük ihtimalle lehine kalacak.',
    'İstatistiksel tablo tek yönlü. Güçsüz tarafın erken pozisyon bulamaması durumunda baskı altında kalmaya devam edebilir.',
  ],
  surpriz: [
    'Net tercih yapmak güç; her iki tarafın da galip gelebileceği bir yapı var. Form dalgalı görünüyor.',
    'Değişken dinamikler bu maçı sürprizlere açık kılıyor. Oranlar ve form birlikte değerlendirilmeli.',
    'İstatistikler net tablo çizmiyor. Bu tür eşleşmelerde sahadaki anlık dinamikler belirleyici rol oynuyor.',
    'Risk seviyesi yüksek. Veriye dayalı senaryo kurmak güç; maç anlık gelişmelere göre şekillenebilir.',
    'Yüksek belirsizlik profili; maçın seyri beklenmedik yönde de değişebilir. Her senaryo eşit derecede geçerli.',
    'Form dalgalı, veriler çelişkili. Sahadaki ruh hali ve motivasyon farkı belirleyici etken olabilir.',
    'İstatistiksel belirsizlik yüksek. Geçmiş karşılaşmalar da net bir kalıp ortaya koymuyor.',
    'Bu tür maçlarda saha dinamikleri çoğu zaman verileri geçersiz kılıyor. Şüpheyle yaklaşmak yerinde olabilir.',
  ],
  savunma: [
    'Bekleyici profiller bu maçı sabırlı ve az gollü bir zemine taşıyor. Her iki takım da yanlış yapmamak önceliğinde.',
    'Savunma dengesinin ön planda olduğu bir karşılaşma bekleniyor. Goller genellikle standart duran toplardan gelebilir.',
    'Disiplinli oyun anlayışı bu maçta temponun düşük kalmasına yol açabilir. Sabır ve pozisyon güvenliği öne çıkıyor.',
    'Her iki takım da kale sıfır geçmişiyle öne çıkıyor. Bu da maçı az gollü senaryoya yaklaştırıyor.',
    'Kontrollü ve dikkatli bir eşleşme bekleniyor. İlk golü bulan taraf yönetmede avantaj kazanacak.',
    'Her iki takım da arkayı sağlam tutmayı tercih ediyor. Hata yapan tarafın bedelini ödemesi kaçınılmaz olabilir.',
    'Savunma eksenli bir eşleşme; temponun düşük tutulması her iki tarafın da çıkarına. İlk golün önemi katlanıyor.',
    'Az gollü zemin bu maçın istatistiksel çerçevesi. Sabit vuruşlar ve pozisyon oyunu belirleyici rol üstlenebilir.',
  ],
  dengeli: [
    'Taraflar benzer istatistiksel tablo çiziyor. Maçın ilk bölümünde temponun kontrollü kalması öne çıkıyor.',
    'Karşılaşma erken kopmaktan çok sabırlı ve dengeli bir akışa daha yakın duruyor. Her iki taraf da pozisyon bekliyor olabilir.',
    'İki ekip de benzer form çiziyor. Oyunun uzun bölümünde kontrolün ön planda kalması beklenebilir.',
    'Maç öncesi göstergeler belirgin fark yaratmıyor. Oyunun seyri açısından sabırlı bir başlangıç öne çıkıyor.',
    'Veriler daha çok kontrollü bir senaryoya yaklaşıyor. Belirleyici bir an gelmedikçe maçın dengeli ilerlemesi olası.',
    'Güç dengesi yakın; maçı koparacak anlık parıltıya kim ulaşır, bunu izlemek gerekiyor.',
    'Profil benzerliği bu karşılaşmayı öngörülmesi güç bir zemine taşıyor. Taktiksel baskı erken gelirse denge bozulabilir.',
    'İstatistiksel tablo bir tarafa net avantaj vermiyor. Sahada kim daha kararlı çıkarsa o tarafa kayabilir.',
  ],
};
