export const SHORT_BANK: Record<string, string[]> = {
  acik: [
    'Maç açık oyuna yakın görünüyor; iki takım da skor üretebilir.',
    'Tempo yüksek, gol sayısı ortalamanın üzerine çıkabilir.',
    'İki hücum hattının da oyuna etki etmesi bekleniyor.',
    'Açılan skor oyunu daha da hareketlendirebilir.',
    'Gollü ve ritmi düşmeyen bir senaryo one çıkıyor.',
    'İki savunma da baskı altinda kalabilir.',
    'Gol beklentisi bu maci digerlerinden ayiriyor.',
    'Karsilikli tehdit üreten bir eşleşme profili var.',
  ],
  kilitli: [
    'Savunma dengesi one çıkıyor; kontrollü bir maç bekleniyor.',
    'Goller kolay gelmeyebilir.',
    'Daha sabırlı ve düşük tempolu bir oyun olası.',
    'Ilk gol gelene kadar denge korunabilir.',
    'Az gollü senaryo verilerle daha uyumlu.',
    'İki takım da hata yapmamaya öncelik verebilir.',
    'Skorun gec acilmasi sasirtici olmaz.',
    'Savunma disiplini bu maçın ana başlığı gibi duruyor.',
  ],
  favori: [
    'Veriler bir tarafi biraz daha önde gösteriyor.',
    'Form ve genel tablo avantajli tarafi destekliyor.',
    'Macin kontrolu tek tarafa daha yakın olabilir.',
    'Üstünlük sinyali net ama kopuk bir maç garanti değil.',
    'Avantajli taraf oyunu kendi ritmine cekebilir.',
    'Taraf sinyali var; yine de tek gollü denge bozulabilir.',
    'Uretim ve savunma dengesi bir ekibi one taşıyor.',
    'Bu eşleşmede ağırlık merkezi bir tarafa kaymis durumda.',
  ],
  surpriz: [
    'Net bir taraf çıkarmak zor; surprize açık bir maç.',
    'Veriler tek yone akmiyor.',
    'Bu eşleşmede küçük anlar sonucu belirleyebilir.',
    'Form ve tablo birbirini tam desteklemiyor.',
    'Belirsizlik seviyesi yüksek.',
    'Maç ici gelismeler yorumdan daha belirleyici olabilir.',
    'İki takım da oyunda kalabilecek profilde.',
    'Bu maci canlı akis daha net anlatabilir.',
  ],
  savunma: [
    'Savunma güvenligi oyunun merkezinde olacak gibi duruyor.',
    'Pozisyon kalitesi sayidan daha önemli olabilir.',
    'Tek golun maci belirleme ihtimali yüksek.',
    'Duran top ve gecis anlari belirleyici olabilir.',
    'İki takım da geride dengeli kalmaya calisacaktir.',
    'Macin ritmini savunma disiplinleri belirleyebilir.',
    'Kontrollü baskı ve hata bekleyen bir yapi var.',
    'Bu tip maçlarda sabır en büyük avantaj olur.',
  ],
  dengeli: [
    'Taraflar birbirine yakın profilde görünüyor.',
    'Macin başlangıcı kontrollü ve dengeli olabilir.',
    'Net üstünlük sinyali cikmiyor.',
    'Ilk gol psikolojik avantaji büyütebilir.',
    'Dengeyi bozan detaylar sonuç üzerinde etkili olacak.',
    'Bu eşleşmede ritim değişimi kritik olabilir.',
    'Form ve tablo birlikte bakildiginda mesafe sınırlı.',
    'Dengeli bir akista sabırlı kalan taraf kazanabilir.',
  ],
  ev_kalesi: [
    'Ev sahibi iç sahada daha güçlü bir profil veriyor.',
    'İç saha etkisi bu maçın yonunu degistirebilir.',
    'Deplasman tarafi disarida daha kırılgan görünüyor.',
    'Tribun ve saha alışkanlığı ev sahibine ekstra destek veriyor.',
    'Ev sahibi kendi ritmini kurarsa üstünlük buyuyebilir.',
    'İç saha performansi sezon ortalamasınin üzerinde.',
    'Bu maçta ev sahibi etkisi dikkate alinmali.',
    'Evde oynayan taraf daha rahat ve daha güvenli görünüyor.',
  ],
  gol_savasi: [
    'İki taraf da gol bulabilir, ama ayni zamanda gol verebilir.',
    'Macin ana hikayesi savunmadan çok skor akışı olabilir.',
    'Açılan oyun daha fazla gol ihtimalini artiriyor.',
    'Savunma kırılganligi bu maci gollü profile taşıyor.',
    'Bu eşleşmede skorun bir kez değil birkaç kez degismesi olası.',
    'Gol odakli bir ritim beklemek daha mantikli.',
    'Hücum gücü ve savunma açıkları ayni anda goruluyor.',
    'İki kale de uzun sure rahat kalmayabilir.',
  ],
  form_donusu: [
    'Son haftalardaki ivme sezon ortalamasından daha güçlü sinyal veriyor.',
    'Form değişimi bu maçın yonunu etkileyebilir.',
    'Güncel ivme, eski tabloyu kismen geçersiz kilabilir.',
    'Son maçlar bir takımı daha diri gösteriyor.',
    'Bu eşleşmede sezon verisi kadar güncel form da önemli.',
    'Yükselen ritim maçın psikolojisini etkileyebilir.',
    'Bir taraf son dönemde daha canlı görünüyor.',
    'Güncel trend bu maça ek anlam katıyor.',
  ],
};

export const MEDIUM_BANK: Record<string, string[]> = {
  acik: [
    'İki takımın da hücum üretimi ve tempo istegi bu maci gollü bir profile taşıyor. Savunma açıkları da bu okumayi destekliyor.',
    'Macin ritmi yüksek görünüyor. Ilk gol gelirse oyun daha da açılabilir ve iki taraf da skora katkı verebilir.',
    'Gol beklentisi ortalamanın üzerinde. Taraf seçiminden çok oyunun açık kalmasi daha güçlü sinyal veriyor.',
    'Hücum profilleri birbirini besliyor. Bu nedenle maçın uzun bölümünde tempo düşmeyebilir.',
    'İki ekip de skor uretmeye yakın görünüyor. Bu tip eşleşmelerde ikinci yari daha fazla alan acabilir.',
    'Veriler, maçın dar skor yerine hareketli bir akışla oynanma ihtimalini güçlendiriyor.',
    'Savunmalarin tam güven vermemesi, gol beklentisini daha anlamli hale getiriyor.',
    'Oyun yapilari birlikte okundugunda bu maci gol senaryosu üzerinden okumak daha tutarli duruyor.',
  ],
  kilitli: [
    'Düşük gol ortalamalari ve kontrollü oyun profili, maci sabır isteyen bir zemine taşıyor. Ilk gol kritik olacak.',
    'İki takım da savunma dengesini bozmadan oynamaya yatkın. Bu nedenle dar skor senaryolari daha doğal görünüyor.',
    'Macin ritmi kolay yukselmeyebilir. Duran top, ikinci top ve bireysel hata oyunu acan temel unsurlar olabilir.',
    'Gol üretimi sınırlı görünüyor. Bu da maci acele etmeyen, hata bekleyen bir yapiya yaklaştırıyor.',
    'Savunma bloklari birbirine yakın seviyede. Bu tip eşleşmelerde oyun uzun sure kilitli kalabilir.',
    'Kontrollü başlangıç ve düşük riskli oyun plani en olası senaryo gibi duruyor.',
    'İki taraf da skor vermemeyi, erken risk almaktan daha öncelikli gorebilir.',
    'Bu profil, seyir olarak sakin ama taktik olarak dikkat isteyen bir maça isaret ediyor.',
  ],
  favori: [
    'Form, puan tablosu ve üretim dengesi birlikte bakildiginda bir taraf digerinden biraz daha önde duruyor. Bu üstünlük oyunun kontrolune yansiyabilir.',
    'Veriler bir ekibi avantajli gösteriyor. Yine de bu avantaj daha çok oyun kontrolu ve kaybetmeme tarafında daha net okunuyor.',
    'Hücum ve savunma dengesi ayni tarafta toplanmis durumda. Bu, maci tek yone yaklastiran en güçlü veri katmani.',
    'Üstünlük sinyali var, fakat maçın tek tarafli akacagi kesin değil. Rakibin oyunda kalma sansi ilk bölümdeki dirence bagli.',
    'Avantajli taraf kendi ritmini kurarsa maç daha okunur hale gelir. Erken gol ise bu farki büyütebilir.',
    'Veriler ağırlığı bir tarafa veriyor. Riski daha dengeli okumak için bu üstünlüğü sonuç kadar oyun kontrolu olarak da düşünmek gerekir.',
    'Taraf sinyali netleşiyor; buna ragmen maçın kopmasi için sahadaki ilk kırılma ani önemli olacak.',
    'Bu eşleşmede genel tablo, bir ekibin daha derli toplu ve daha güvenli geldigini soyluyor.',
  ],
  surpriz: [
    'Bu eşleşmede net bir taraf yorumuna gitmek zor. Form, savunma ve tempo verileri ayni yone güçlü bicimde bakmiyor.',
    'Belirsizlik seviyesi yüksek. Bu nedenle maci sadece pre-match verilerle değil, oyun ici akışla birlikte okumak daha sağlıklı olur.',
    'İki takım da farklı alanlarda avantaj taşıyor. Bu durum, maçın sonucunu küçük anlara ve karar kalitesine birakiyor.',
    'Veriler birbirini tam desteklemiyor. Bu tip maçlarda ilk gol, kirmizi kart ya da duran top gibi anlar yorumun önüne geçebilir.',
    'Taraf seçmekten çok riskin yüksek oldugunu not etmek daha dogru. Canlı ritim burada daha değerli bilgi üretir.',
    'Form dalgalı, tablo tam net değil. Bu da maci surprize açık ve yorumu zor bir profile taşıyor.',
    'Bu eşleşmede tek bir senaryoya fazla guvenmek dogru olmaz. Oyun ici denge çok cabuk değişebilir.',
    'Maç öncesi tablo kesin bir sonuç soylemiyor; daha çok olasılıklarin birbirine yakın oldugu bir yapı sunuyor.',
  ],
  savunma: [
    'Savunma güvenligi bu eşleşmenin ana ekseni gibi görünüyor. Oyun uzun sure kontrollü ve parçalı akabilir.',
    'İki takım da geride alan vermemeye odaklanirsa, maçın temposu belirgin sekilde düşük kalabilir.',
    'Bu tip profillerde pozisyon sayısından çok pozisyon kalitesi önem kazanir. Tek bir duran top bile dengeyi bozabilir.',
    'Mac, hücum gosterisinden çok savunma organizasyonu ve sabır üzerinden okunuyor.',
    'Skor üretimi sınırlı, savunma dikkati ise yüksek. Bu da dar skor ihtimalini güçlendiriyor.',
    'İki taraf da hata yapmamak isteyecektir. Bu nedenle ilk gol gelene kadar oyun temkinli kalabilir.',
    'Savunma verileri, bu maçın açık oyundan çok disiplinli yerlesimle ilerleyebileceğini gösteriyor.',
    'Macin ana sorusu kim daha çok pozisyon bulacak değil, kim tek kritik ani daha iyi yönetecek sorusu olabilir.',
  ],
  dengeli: [
    'Taraflarin genel profili birbirine yakın. Macin ritmini bozacak asıl unsur, ilk gol ya da ikinci yari ayarlari olabilir.',
    'Maç öncesi tablo belirgin bir taraf üstünlüğü vermiyor. Bu da oyunu denge ve sabır eksenine taşıyor.',
    'İki ekip de benzer güçlü ve zayif alanlar taşıyor. Bu nedenle maçın uzun bölümünde denge korunabilir.',
    'Veriler, kopmaktan çok olgunlaşarak açılan bir maça isaret ediyor. Taktiksel detaylar fark yaratacak.',
    'Dengeli profilde ilk yarinin daha dikkatli geçmesi, ikinci yarida ise risk seviyesinin artis göstermesi olası.',
    'Bu maci tek bir sayiya bakarak okumak zor. Form, savunma ve gol beklentisi birbirine yakın bir resim veriyor.',
    'Taraflar arasindaki mesafe sınırlı. Bu nedenle oyun ici momentum, maçın yorumundan daha hızlı ağırlık kazanabilir.',
    'Denge bozulursa genelde tek bir veri değil, birkaç küçük detay ust uste gelerek bozulacak gibi duruyor.',
  ],
  ev_kalesi: [
    'Ev sahibi kendi sahasında daha güçlü bir profil veriyor. Bu üstünlük sadece his değil, performans verileriyle de destekleniyor.',
    'İç saha etkisi bu maçta gercek bir avantaj üretiyor. Ev sahibi kendi ritmine daha kolay ulasabilir.',
    'Deplasman takımınin dis saha performansi daha kırılgan. Bu nedenle maçın doğal akışı ev sahibi lehine kayabilir.',
    'Tribun, saha alışkanlığı ve iç saha verimi bir araya geldiginde ev sahibi tarafın zemini daha saglam görünüyor.',
    'Ev sahibi evinde daha rahat üretim yaparken deplasman tarafi disarida daha fazla savunma baskısı yasayabiliyor.',
    'Bu eşleşmede ev sahibi etkisi psikolojik değil, sayısal olarak da hissediliyor.',
    'İç saha performansi, sezon genel dengesine ekstra ağırlık katıyor. Bu da maçın yonunu etkileyecek temel faktörlürden biri.',
    'Ev sahibi oyun kontrolunu kurarsa bu maci kendi kosullarina daha kolay tasiyabilir.',
  ],
  gol_savasi: [
    'İki takım da gol atma konusunda istekli, gol yeme konusunda ise tam güven vermiyor. Bu profil maci gollü senaryoya yaklaştırıyor.',
    'Savunma kırılganligi iki tarafta da hissediliyor. Bu nedenle maçın ana başlığı skor akışı olabilir.',
    'Gol ortalamalari ve yenilen gol yapisi birlikte bakildiginda oyun acildikca daha hareketli hale gelebilir.',
    'Bu tip eşleşmelerde ilk gol genelde frene değil, daha da hızlanan bir ritme neden olur.',
    'İki taraf da top rakipteyken rahat hissettirmiyor. Bu da gol beklentisini doğal bicimde yükseltiyor.',
    'Macin hikayesi savunmadan çok hücum cevabi üzerinden yazilabilir. Karsilikli skor ihtimali yüksek.',
    'Hem tempo hem bitiricilik potansiyeli bu maci gol odakli bir profile taşıyor.',
    'Bu eşleşmede "gol olur mu" sorusundan çok "oyun ne kadar açılır" sorusu daha anlamli duruyor.',
  ],
  form_donusu: [
    'Son haftalardaki ivme sezon geneline gore farklı bir hikaye anlatiyor. Bu nedenle güncel form burada ekstra ağırlık kazaniyor.',
    'Bir tarafın son dönem çıkışi, kağıt üstündeki sezon dengesini degistirebilir. Maci güncel ritimle birlikte okumak gerekiyor.',
    'Form grafiği değişen takımlar, sezon ortalamasından daha farklı bir oyun seviyesi getirebilir. Bu maç da o profile yakın.',
    'Son maçlardaki momentum farki, oyunun psikolojisini ve ozgüven dengesini etkileyebilir.',
    'Bu eşleşmede güncel form, genel tablo kadar önemli. İvmeyi yakalayan taraf saha içinde daha cesur davranabilir.',
    'Bir takımın son dönemdeki toparlanması ya da dususu, bu maci normalden daha değişken hale getiriyor.',
    'Form dönüşümu bu maçın yorumunda temel katmanlardan biri. Sadece sezon toplamlarina bakmak eksik kalir.',
    'Son haftalarda güçlenen taraf, bu maça rakibinden daha canlı ve daha net planla çıkabilir.',
  ],
};
